version: '3.1'
services:
  backend:
    env_file:
      - secrets.env
    build: .
    container_name: PiguBackend
    ports:
      - 3200:3200

  db:
    image: mariadb
    container_name: PiguDB
    restart: always
    volumes:
       - /root/mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - 3306:3306
